swagger: "2.0"
info:
  description: "This is the Mindsmiths HTTP API specification."
  version: "1.0.0"
  title: "Mindsmiths HTTP API"
  termsOfService: ""
  contact:
    email: "hello@mindsmiths.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
- name: "signals"
  description: "Sending messages and events"
- name: "agents"
  description: "Managing agents"
schemes:
- "https"
- "http"
paths:
  /message/{to}:
    post:
      tags:
      - "signals"
      summary: "Sends a message to an agent"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "to"
        in: "path"
        description: "ID of agent to send the message to"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Message to send"
        required: true
        schema:
          $ref: "#/definitions/Message"
      responses:
        "200":
          description: "Success"
        "422":
          description: "Validation failed"
  /message/{to}/{messageType}:
    post:
      tags:
      - "signals"
      summary: "Sends a message to an agent"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "to"
        in: "path"
        description: "ID of agent to send the message to"
        required: true
        type: "string"
      - name: "messageType"
        in: "path"
        description: "The message type (used for type-casting)"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Message to send"
        required: true
        schema:
          $ref: "#/definitions/AnyBody"
      responses:
        "200":
          description: "Success"
        "422":
          description: "Validation failed"
  
  /event:
    post:
      tags:
      - "signals"
      summary: "Emits an event"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Event to emit"
        required: true
        schema:
          $ref: "#/definitions/Event"
      responses:
        "200":
          description: "Success"
        "422":
          description: "Validation failed"
  /event/{eventType}:
    post:
      tags:
      - "signals"
      summary: "Emits an event"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "eventType"
        in: "path"
        description: "The event type (used for type-casting)"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Event to emit"
        required: true
        schema:
          $ref: "#/definitions/AnyBody"
      responses:
        "200":
          description: "Success"
        "422":
          description: "Validation failed"
  
  /agent/{agent}:
    post:
      tags:
      - "agents"
      summary: "Creates a new agent"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "agent"
        in: "path"
        description: "Type of agent to create"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Agent parameters"
        required: true
        schema:
          $ref: "#/definitions/AnyBody"
      responses:
        "200":
          description: "Success"
    put:
      tags:
      - "agents"
      summary: "Updates an agent"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "agent"
        in: "path"
        description: "ID of agent to update"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Values to update"
        required: true
        schema:
          $ref: "#/definitions/AnyBody"
      responses:
        "200":
          description: "Success"
    delete:
      tags:
      - "agents"
      summary: "Deletes an agent"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "agent"
        in: "path"
        description: "ID of agent to delete"
        required: true
        type: "string"
      responses:
        "200":
          description: "Success"

definitions:
  Message:
    type: "object"
    required:
    - messageType
    properties:
      messageType:
        type: "string"
    additionalProperties:
      $ref: "#/definitions/AnyValue"
    example:
      messageType: "Register"
      userId: "user-id"
      code: 8765
      
  Event:
    type: "object"
    required:
    - eventType
    properties:
      eventType:
        type: "string"
    additionalProperties:
      $ref: "#/definitions/AnyValue"
    example:
      messageType: "UserRegistered"
      userId: "user-id"
      code: 8765
      
  AnyBody:
    type: "object"
    additionalProperties:
      $ref: "#/definitions/AnyValue"
    example:
      userId: "user-id"
      code: 8765

  AnyValue: {}

externalDocs:
  description: "Find out more in Mindsmiths Docs"
  url: "http://docs.mindsmiths.io"